name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Get variables
        id: get_vars
        run: |
          echo '::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)'
          echo '::set-output name=DATE::$(date +'%D')'

      - name: Bump manifest version
        run: node .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: bump manifest version to ${{ github.ref_name }}"

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ github.ref_name }}

      - name: Bundle files
        run: |
          mkdir -p ./temp/sleepless_interact
          mkdir -p ./temp/sleepless_interact/web
          cp ./{README.md,LICENSE,fxmanifest.lua,init.lua,__types.lua} ./temp/sleepless_interact
          cp -r ./{bridge,classes,client,server,exports,imports} ./temp/sleepless_interact
          cp -r ./web ./temp/sleepless_interact/web
          cd ./temp && zip -r ../sleepless_interact.zip ./sleepless_interact

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        id: auto_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: sleepless_interact.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}